'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const URL_ROOT='https://wyoamcydkbblvujvyljs.supabase.co';
const PUBLIC_KEY='sb_publishable_DApk1ZNyEUeBhpeBwHgM8g_uKaMnXzS';
const client=window.supabase.createClient(URL_ROOT,PUBLIC_KEY);
const APP_VERSION=Number(document.querySelector('#appVersion').textContent);
const state={pickingFile:false,session:null,tab:'editing',kind:'etsy',projects:[],masters:[],connections:[],busy:new Set(),generation:0};
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=value=>{try{const url=new URL(value);return url.protocol==='https:'?url.href:'';}catch{return '';}};
function notify(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').hidden=true,6500);}
async function request(endpoint,body){if(!state.session)throw Error('Sign in to continue.');const response=await fetch(URL_ROOT+'/functions/v1/'+endpoint,{method:'POST',headers:{authorization:'Bearer '+state.session.access_token,apikey:PUBLIC_KEY,'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(150000)});const data=await response.json();if(!response.ok||data.error)throw Error(data.error?.message||data.error||'Request failed.');return data;}
async function tool(name,args={}){const data=await request('seller-tools-inbox',{jsonrpc:'2.0',id:crypto.randomUUID(),method:'tools/call',params:{name,arguments:args}});if(data.result?.isError)throw Error(data.result.content?.[0]?.text||'Request failed.');return data.result?.structuredContent||JSON.parse(data.result?.content?.find(x=>x.type==='text')?.text||'{}');}
async function load(){if(state.pickingFile||state.busy.size)return;const generation=++state.generation;$('#refresh').disabled=true;try{const [projects,masters,connections]=await Promise.all([client.from('review_projects').select('*').in('kind',['etsy','pinterest']).order('updated_at',{ascending:false}),tool('list_master_files',{}),client.from('platform_connections').select('platform,status,metadata').in('platform',['etsy','pinterest'])]);if(projects.error)throw projects.error;if(connections.error)throw connections.error;if(generation!==state.generation||!state.session)return;state.projects=(projects.data||[]).filter(p=>!p.manifest?.archived&&p.status!=='published');state.masters=masters.masters||[];state.connections=connections.data||[];await hydrate();if(generation!==state.generation||!state.session)return;render();}catch(error){notify(error.message);}finally{$('#refresh').disabled=false;}}
async function hydrate(){for(const kind of ['etsy','pinterest']){const rows=state.projects.filter(p=>p.kind===kind),paths=[...new Set(rows.flatMap(p=>(p.media||[]).map(x=>x.path)).filter(Boolean))];if(!paths.length)continue;const {data,error}=await client.storage.from(kind==='etsy'?'etsy-assets':'pinterest-media').createSignedUrls(paths,900);if(error)throw error;const urls=new Map(data.map(x=>[x.path,x.signedUrl]));rows.forEach(p=>p.urls=Object.fromEntries((p.media||[]).map(x=>[x.role,urls.get(x.path)])));}}
function route(){const tab=location.hash.slice(1);state.tab=['editing','posting','storage'].includes(tab)?tab:'editing';render();}
function render(){if(!state.session||state.pickingFile)return;const labels={editing:['REFINE YOUR LISTINGS','Editing','Review the details. Approve the changes.'],posting:['READY FOR YOUR AUDIENCE','Posting','Your next listing or pin, ready for its moment.'],storage:['YOUR PRIVATE COLLECTION','Storage','Your blueprint and current planner Word documents.']};const [label,title,copy]=labels[state.tab];$('#section-label').textContent=label;$('#section-title').textContent=title;$('#section-copy').textContent=copy;$$('[data-tab]').forEach(b=>{if(b.dataset.tab===state.tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('#posting-filter').hidden=state.tab!=='posting';$$('[data-kind]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===state.kind)));const pinterest=state.connections.find(x=>x.platform==='pinterest');$('#connection-message').hidden=!(state.tab==='posting'&&state.kind==='pinterest'&&pinterest?.status!=='connected');$('#connection-message').textContent='Pinterest is awaiting connection approval. Your pins can be reviewed here; posting becomes available once connected.';if(state.tab==='storage')return renderStorage();const rows=state.projects.filter(p=>state.tab==='editing'?p.kind==='etsy'&&p.manifest?.mode==='edit':p.kind===state.kind&&p.manifest?.mode!=='edit');$('#content').innerHTML=rows.length?`<div class="grid">${rows.map(card).join('')}</div>`:`<div class="empty"><h2>Everything in its place.</h2><p>${state.tab==='editing'?'Send a title, description, image or PDF update from ChatGPT to review it here.':'Send your completed listing or pin from ChatGPT to review it here.'}</p></div>`;}
function card(p){const m=p.manifest||{},role=m.imageReplacements?.[0]?.role||m.pins?.[0]?.imageRole||'thumbnail',src=safeUrl(p.urls?.[role]||m.existingImages?.[0]?.url);return `<article class="card">${src?`<img src="${escapeHtml(src)}" alt="${escapeHtml(m.imageReplacements?.[0]?.altText||m.pins?.[0]?.altText||p.title)}" loading="lazy">`:`<div class="placeholder">${p.kind==='pinterest'?'A new perspective.':'The next chapter.'}</div>`}<div class="card-body"><span class="tag">${escapeHtml(p.status==='published'?'Published':p.status==='ready'?'Ready for review':p.status==='failed'?'Needs attention':p.status==='publishing'?'Checking publication':'Preparing')}</span><h3>${escapeHtml(p.title)}</h3><p>${m.mode==='edit'?escapeHtml((m.updateScope||[]).map(x=>({files:'PDF',images:'Listing images',alt_text:'Alt text'}[x]||x)).join(' · ')):p.kind==='pinterest'?'Pinterest pin':'New Etsy listing'}</p><button data-review="${p.id}">Review ${m.mode==='edit'?'changes':p.kind==='pinterest'?'pin':'listing'}</button></div></article>`;}
const image=(url,alt)=>safeUrl(url)?`<img class="review-image" src="${escapeHtml(safeUrl(url))}" alt="${escapeHtml(alt)}">`:'<p class="notice">Preview unavailable. Refresh before approving.</p>';
function compare(label,before,after,isImage=false,beforeAlt='',afterAlt=''){return `<h3>${escapeHtml(label)}</h3><div class="comparison"><div><p class="eyebrow">CURRENT</p>${isImage?image(before,beforeAlt):`<p class="copy">${escapeHtml(before)}</p>`}${isImage?`<p class="caption">${escapeHtml(beforeAlt)}</p>`:''}</div><div><p class="eyebrow">PROPOSED</p>${isImage?image(after,afterAlt):`<p class="copy">${escapeHtml(after)}</p>`}${isImage?`<p class="caption">${escapeHtml(afterAlt)}</p>`:''}</div></div>`;}
function openReview(id){const p=state.projects.find(x=>x.id===id);if(!p)return;const m=p.manifest||{};let body=`<h2>${escapeHtml(p.title)}</h2>`;if(m.mode==='edit'){for(const [key,value] of Object.entries(m.updateFields||{}))body+=compare(key,m.existingSnapshot?.[key],value);for(const replacement of m.imageReplacements||[]){const old=m.existingImages?.find(x=>Number(x.rank)===Number(replacement.rank));body+=compare(Number(replacement.rank)===1?'Thumbnail':`Listing image · position ${replacement.rank}`,old?.url,p.urls?.[replacement.role],true,old?.altText,replacement.altText);}for(const alt of m.altTextUpdates||[]){const old=m.existingImages?.find(x=>x.id===alt.listingImageId);body+=compare(`Alt text · position ${alt.rank}`,old?.altText,alt.altText);}for(const file of m.fileUpdates||[]){const old=m.existingFiles?.find(x=>x.id===file.listingFileId);body+=compare('Customer PDF',old?.name,file.filename);body+=`<a href="${escapeHtml(safeUrl(p.urls?.[file.role]))}" target="_blank" rel="noopener">Preview proposed PDF</a>`;}}else if(p.kind==='pinterest'){for(const pin of m.pins||[]){body+=image(p.urls?.[pin.imageRole||'pin-1'],pin.altText||pin.title)+`<h3>${escapeHtml(pin.title)}</h3><p class="copy">${escapeHtml(pin.description)}</p><p>Board: <strong>${escapeHtml(pin.board)}</strong></p><a href="${escapeHtml(safeUrl(pin.link))}" target="_blank" rel="noopener">Open planner on Etsy</a>`;}}else{body+=`<p>Price: ${escapeHtml(m.listingDefaults?.currency||'GBP')} ${escapeHtml(m.price)} · Digital download</p><p class="copy">${escapeHtml(m.description)}</p><p class="caption">${escapeHtml((m.tags||[]).join(' · '))}</p><div class="grid">`;['thumbnail',...Array.from({length:5},(_,i)=>'listing-image-'+(i+1))].forEach((role,i)=>body+=`<div>${image(p.urls?.[role],m.altText?.[i])}<p class="caption">${escapeHtml(m.altText?.[i])}</p></div>`);body+=`</div><p><a href="${escapeHtml(safeUrl(p.urls?.['customer-pdf']))}" target="_blank" rel="noopener">Preview customer PDF</a></p>`;}
if(p.status==='failed'&&m.mode==='edit'){body+=`<button data-check-result="${id}">Check Etsy result</button>`;if(m.updateScope?.length===1&&m.updateScope[0]==='images')body+=`<button class="primary" data-resume-images="${id}" ${state.busy.has(id)?'disabled':''}>Finish approved image update</button>`;}
if(p.last_error)body+=`<p class="notice">${escapeHtml(p.last_error)}</p>`;if(p.status==='published'){const url=safeUrl(p.platform_url||m.publishedUrl||(p.platform_id?(p.kind==='etsy'?'https://www.etsy.com/listing/':'https://www.pinterest.com/pin/')+p.platform_id:''));body+=url?`<p><a href="${escapeHtml(url)}" target="_blank" rel="noopener">Open published ${p.kind==='etsy'?'listing':'pin'}</a></p>`:'<p>Published.</p>';}else{const connected=state.connections.find(x=>x.platform===p.kind)?.status==='connected';body+=`<div class="review-actions"><button class="danger" data-cancel="${id}" ${p.status==='publishing'?'disabled':''}>Cancel & delete</button><button class="primary" data-approve="${id}" ${p.status!=='ready'||!connected||state.busy.has(id)?'disabled':''}>${p.kind==='etsy'&&m.mode==='edit'?'Approve changes':'Approve & publish'}</button></div>`;}$('#review-content').innerHTML=body;if(!$('#review').open)$('#review').showModal();}
async function approve(id){if(state.busy.has(id))return;const p=state.projects.find(x=>x.id===id);if(!p||p.status!=='ready')return;state.busy.add(id);openReview(id);try{await request(p.kind==='etsy'?'etsy-publish':'pinterest-publish',{project_id:id,expected_revision:p.revision});notify('Publication confirmed.');}catch(error){notify(error.name==='TimeoutError'?'Confirmation is taking longer. Refresh to check the result before retrying.':error.message);}finally{state.busy.delete(id);await load();if(state.projects.some(p=>p.id===id))openReview(id);else $('#review').close();}}
async function cancel(id){if(state.busy.has(id))return;state.busy.add(id);try{await tool('clear_review_project',{project_id:id,confirmed:true});$('#review').close();await load();notify('Submission deleted.');}catch(error){notify(error.message);}finally{state.busy.delete(id);}}
function renderStorage(){const blueprints=state.masters.filter(m=>m.category==='blueprint');const rows=[...(blueprints.length?blueprints:[{id:'blueprint-new',category:'blueprint',title:'Planner & Listing Blueprint',files:[]}]),...state.masters.filter(m=>m.category!=='blueprint')];$('#content').innerHTML=rows.map(m=>{const doc=(m.files||[]).find(x=>x.role==='docx');return `<article class="storage-row"><div><span class="eyebrow">${m.category==='blueprint'?'BLUEPRINT':'WORD DOCUMENT'}</span><h3>${escapeHtml(m.category==='blueprint'&&doc?.name==='Blank_Itinerary_Master_Template.docx'?'Blank planner template':m.title)}</h3><p>${doc?escapeHtml(doc.name):'No Word document saved yet'}</p></div><div class="storage-actions">${doc?`<button data-download="${m.id}">Download</button>`:''}<button data-upload="${m.id}">${doc?'Replace':'Upload'} DOCX</button>${doc?`<button class="danger" data-delete="${m.id}">Delete</button>`:''}<input class="upload" type="file" id="file-${m.id}" data-master="${m.id}" accept=".docx"></div></article>`;}).join('');}
async function download(id){const data=await tool('get_master_file',{master_id:id});const doc=data.master.files.find(x=>x.role==='docx');if(!doc)throw Error('No DOCX is saved for this planner.');location.assign(safeUrl(doc.download_url));}
async function upload(id,file){if(!file)return;if(!/\.docx$/i.test(file.name))throw Error('Choose a Word DOCX file.');if(state.busy.has(id))return;state.busy.add(id);const uploadButton=$$('[data-upload]').find(b=>b.dataset.upload===id);if(uploadButton){uploadButton.disabled=true;uploadButton.textContent='Uploading…';}notify('Uploading '+file.name+'…');try{if(id==='blueprint-new'){const created=await tool('create_master_file',{category:'blueprint',title:'Planner & Listing Blueprint'});id=created.master.id;}const current=await tool('get_master_file',{master_id:id}),bytes=await file.arrayBuffer(),checksum=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');const batch=await tool('prepare_master_upload',{master_id:id,expected_revision:current.current_revision,reason:'Replace current private Word backup',idempotency_key:'docx-'+id+'-'+current.current_revision+'-'+checksum.slice(0,32),files:[{role:'docx',filename:file.name,size:file.size,checksum}]});if(!batch.already_committed){const response=await fetch(batch.files[0].upload_url,{method:'PUT',headers:{'content-type':batch.files[0].mime,'x-upsert':'false'},body:bytes});if(!response.ok&&response.status!==409)throw Error('File upload failed. The current backup is unchanged.');await tool('commit_master_upload',{upload_id:batch.upload_id});}notify('Current Word backup saved.');}finally{state.busy.delete(id);state.busy.delete('blueprint-new');await load();}}
async function deleteDoc(id){if(!confirm('Permanently delete this current Word document?'))return;const current=await tool('get_master_file',{master_id:id});await tool('delete_master_file',{master_id:id,expected_revision:current.current_revision});await load();notify('Word backup deleted.');}
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;try{if(b.dataset.tab)location.hash=b.dataset.tab;if(b.dataset.kind){state.kind=b.dataset.kind;render();}if(b.dataset.resumeImages)await resumeImages(b.dataset.resumeImages);if(b.dataset.checkResult)await checkResult(b.dataset.checkResult);if(b.dataset.review)openReview(b.dataset.review);if(b.dataset.approve)await approve(b.dataset.approve);if(b.dataset.cancel)await cancel(b.dataset.cancel);if(b.dataset.download)await download(b.dataset.download);if(b.dataset.upload)chooseDoc(b.dataset.upload);if(b.dataset.delete)await deleteDoc(b.dataset.delete);}catch(error){notify(error.message);}});
function chooseDoc(id){if(state.busy.size||state.pickingFile)return;const input=$('#file-'+id);if(!input)return;state.pickingFile=true;state.generation++;document.body.append(input);input.value='';input.addEventListener('cancel',()=>{state.pickingFile=false;input.remove();render();},{once:true});try{input.click();}catch(error){state.pickingFile=false;input.remove();render();throw error;}}
document.addEventListener('change',async event=>{const input=event.target;if(!input.dataset.master)return;const id=input.dataset.master,file=input.files[0];state.pickingFile=false;input.remove();try{await upload(id,file);}catch(error){notify(error.message);}finally{if(!file)render();}});
$('#signin-form').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{const {error}=await client.auth.signInWithOtp({email:$('#email').value.trim(),options:{shouldCreateUser:false,emailRedirectTo:location.origin+location.pathname}});$('#auth-message').textContent=error?error.message:'Check your email for your secure sign-in link.';}finally{button.disabled=false;}};
$('#refresh').onclick=load;$('#account').onclick=()=>{if(!state.session)return;$('#account-email').textContent=state.session.user.email;$('#account-connections').textContent=state.connections.map(x=>`${x.platform}: ${x.status.replaceAll('_',' ')}`).join(' · ');$('#account-dialog').showModal();};$('#signout').onclick=()=>client.auth.signOut();window.addEventListener('hashchange',route);
client.auth.onAuthStateChange((_event,session)=>{state.session=session;$('#signin').hidden=!!session;$('#workspace').hidden=!session;$('#navigation').hidden=!session;if(session){route();setTimeout(load,0);}else{state.generation++;state.projects=[];state.masters=[];$('#content').innerHTML='';$$('dialog').forEach(d=>d.close());}});

$('#connect-pinterest').onclick=async()=>{try{const result=await request('pinterest-oauth',{});location.assign(safeUrl(result.url));}catch(error){notify(error.message);}};

// Refresh the application shell without caching private API responses or assets.
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(registration=>registration.update()).catch(()=>{});}
async function checkRelease(){try{const response=await fetch('./release.json?t='+Date.now(),{cache:'no-store'});if(!response.ok)return;const release=await response.json();if(release.app_version>APP_VERSION&&!state.busy.size&&!state.pickingFile){location.reload();}}catch{}}
window.addEventListener('focus',()=>{if(state.pickingFile||state.busy.size)return;checkRelease();if(state.session&&!state.busy.size)load();});

async function checkResult(id){const p=state.projects.find(p=>p.id===id);if(!p)return;try{const result=await request('etsy-publish',{action:'check_result',project_id:id,expected_revision:p.revision});if(result.verified){notify('Etsy matches the approved update.');await load();if(state.projects.some(p=>p.id===id))openReview(id);else $('#review').close();return;}const container=$('#review-content');container.insertAdjacentHTML('beforeend',`<p class="notice">${escapeHtml(result.message)}</p><p><a href="${escapeHtml(safeUrl(result.listing_url))}" target="_blank" rel="noopener">Inspect the live Etsy listing</a></p>`);if(result.run_id){const button=document.createElement('button');button.textContent='I checked Etsy — delete this submission';button.className='danger';button.onclick=async()=>{try{await request('etsy-publish',{action:'acknowledge_run',run_id:result.run_id,confirmed_review:true});await cancel(id);}catch(error){notify(error.message);}};container.append(button);}}catch(error){notify(error.message);}}

async function resumeImages(id){if(state.busy.has(id))return;const p=state.projects.find(x=>x.id===id);if(!p||p.status!=='failed')return;state.busy.add(id);openReview(id);try{await request('etsy-publish',{action:'resume_images',project_id:id,expected_revision:p.revision});notify('Images and alt text verified on Etsy.');}catch(error){notify(error.message);}finally{state.busy.delete(id);await load();if(state.projects.some(x=>x.id===id))openReview(id);else $('#review').close();}}
