const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {stripTypeScriptTypes}=require('node:module');
function context(){const ctx=vm.createContext({crypto,Uint8Array,TextDecoder,TextEncoder,URL,AbortSignal,Blob,Date,Set,Map,fetch,unzipSync:require('fflate').unzipSync,zipSync:require('fflate').zipSync});for(const file of ['storage-cleanup.ts','master-files.ts'])vm.runInContext(stripTypeScriptTypes(fs.readFileSync('supabase/functions/seller-tools-inbox/'+file,'utf8').replace(/^import .*?;\s*$/gm,'').replace(/\bexport /g,'')),ctx);return ctx;}
function query(data){const q={select(){return q},eq(){return q},order(){return q},limit(){return q},maybeSingle:async()=>({data}),single:async()=>({data}),then(f){return Promise.resolve({data}).then(f)}};return q;}
test('removed storage actions are rejected before any database or file access',async()=>{const ctx=context();for(const name of ['restore_master_version','import_review_images_to_master','attach_master_files_to_review'])await assert.rejects(ctx.handleMasterTool(name,{},{}),/no longer supported/);});
test('PDF and image uploads cannot reserve storage',async()=>{const ctx=context(),db={from:()=>query({id:'planner',revision:0})};for(const ext of ['pdf','png'])await assert.rejects(ctx.handleMasterTool('prepare_master_upload',{master_id:'planner',expected_revision:0,reason:'Save',files:[{role:ext,filename:'Guide.'+ext,size:20,checksum:'a'.repeat(64)}]},{db,admin:{},userId:'owner'}),/one Word DOCX/);});
test('past revisions cannot be retrieved',async()=>{const ctx=context(),db={from:()=>query({id:'planner',revision:3,files:[]})};await assert.rejects(ctx.handleMasterTool('get_master_file',{master_id:'planner',revision:1},{db,userId:'owner'}),/Only the current/);});
test('failed object cleanup keeps its durable job for retry',async()=>{const ctx=context();let deleted=false;const admin={from(){const q=query([{id:'job',bucket:'seller-master-files',path:'owner/planner/old.docx'}]);q.delete=()=>{deleted=true;return q};return q},storage:{from:()=>({remove:async()=>({error:Error('offline')})})}};await assert.rejects(ctx.drainStorageCleanup(admin,'owner'),/cleanup is pending/);assert.equal(deleted,false);});
test('cleanup rejects paths owned by someone else',async()=>{const ctx=context(),admin={from:()=>query([{id:'job',bucket:'seller-master-files',path:'other/planner/doc.docx'}]),storage:{from(){throw Error('must not touch storage')}}};await assert.rejects(ctx.drainStorageCleanup(admin,'owner'),/ownership/);});
test('successful cleanup removes its job only after removing the object',async()=>{const ctx=context(),calls=[];const admin={from(){const q=query([{id:'job',bucket:'seller-master-files',path:'owner/planner/old.docx'}]);q.delete=()=>{calls.push('job');return q};return q},storage:{from:()=>({remove:async()=>{calls.push('object');return {error:null}}})}};await ctx.drainStorageCleanup(admin,'owner');assert.deepEqual(calls,['object','job']);});

test('DOCX save validates archive contents as well as SHA-256',async()=>{const ctx=context(),zip=require('fflate').zipSync;const make=bytes=>({name:'Planner.docx',mime:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',size:bytes.length,checksum:require('node:crypto').createHash('sha256').update(bytes).digest('hex')});const wrong=zip({'random.txt':new TextEncoder().encode('not Word')});await assert.rejects(ctx.verifyMasterBytes(make(wrong),wrong),/not a Word DOCX/);const good=zip({'[Content_Types].xml':new TextEncoder().encode('<Types/>'),'word/document.xml':new TextEncoder().encode('<document/>')});await ctx.verifyMasterBytes(make(good),good);await assert.rejects(ctx.verifyMasterBytes({...make(good),checksum:'a'.repeat(64)},good),/checksum/);});
test('save identity is stable and isolated by planner and owner',async()=>{const ctx=context();const a=await ctx.uploadIdentity('owner','planner','save-0001');assert.equal(a,await ctx.uploadIdentity('owner','planner','save-0001'));assert.notEqual(a,await ctx.uploadIdentity('owner','other','save-0001'));assert.notEqual(a,await ctx.uploadIdentity('other','planner','save-0001'));});
