const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {JSDOM}=require('jsdom');
const root=path.join(__dirname,'..');
function app(){const html=fs.readFileSync(path.join(root,'index.html'),'utf8');const dom=new JSDOM(html,{url:'https://example.test/?demo=1',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;let calls=0;w.structuredClone=structuredClone;w.confirm=()=>true;w.scrollTo=()=>{};w.fetch=()=>{calls++;throw Error('Demo attempted a live request');};w.supabase={createClient:()=>({auth:{}})};const script=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1];for(const source of [script,fs.readFileSync(path.join(root,'core.js'),'utf8'),fs.readFileSync(path.join(root,'workspace.js'),'utf8')])require('node:vm').runInContext(source,dom.getInternalVMContext());return {w,dom,calls:()=>calls};}
test('sample workspace renders real interface without querying private services',()=>{const {w,dom,calls}=app();assert.equal(w.document.querySelectorAll('.listingcard').length,2);assert.match(w.document.querySelector('#syncState').textContent,/Sample mode/);assert.equal(calls(),0);dom.window.close();});

function masters(){const a=app();vmLoad(a,'master-files.js');return a;}
function vmLoad(a,file){require('node:vm').runInContext(fs.readFileSync(path.join(root,file),'utf8'),a.dom.getInternalVMContext());}
test('master search and history work without any private network requests',async()=>{
 const {w,dom,calls}=masters();assert.equal(w.document.querySelectorAll('.mastercard').length,2);
 await w.MasterFiles.open('demo-master');assert.match(w.document.querySelector('#masterBody').textContent,/Sample_Guide.docx/);assert.match(w.document.querySelector('#masterBody').textContent,/Sample_Guide.pdf/);
 await w.MasterFiles.open('demo-master',1);assert.match(w.document.querySelector('#masterBody').textContent,/Earlier Version/);assert.equal(w.document.querySelector('#masterUploadForm'),null);
 await w.MasterFiles.restore(1);assert.match(w.document.querySelector('.masterdetailtop').textContent,/Version 3/);assert.equal(calls(),0);dom.window.close();
});
test('master replacement saves both files and preserves an earlier downloadable revision',async()=>{
 const {w,dom,calls}=masters();await w.MasterFiles.open('demo-master');const input=w.document.querySelector('#masterUploadInput');
 Object.defineProperty(input,'files',{value:[new w.File(['word'],'Updated_Guide.docx',{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),new w.File(['pdf'],'Updated_Guide.pdf',{type:'application/pdf'})]});input.dispatchEvent(new w.Event('change'));
 w.document.querySelector('#masterUploadForm [name="reason"]').value='Updated accommodation';await w.document.querySelector('#masterUploadForm').onsubmit({preventDefault(){},currentTarget:w.document.querySelector('#masterUploadForm')});
 assert.match(w.document.querySelector('#masterBody').textContent,/Updated_Guide.docx/);assert.match(w.document.querySelector('#masterBody').textContent,/Updated_Guide.pdf/);
 await w.MasterFiles.open('demo-master',2);assert.match(w.document.querySelector('#masterBody').textContent,/Sample_Guide.docx/);assert.equal(calls(),0);dom.window.close();
});
test('reset clears master metadata from the signed-out interface',async()=>{const {w,dom}=masters();await w.MasterFiles.open('demo-master');w.MasterFiles.reset();assert.doesNotMatch(w.document.querySelector('#masterGrid').textContent,/Coastal Journey/);assert.equal(w.document.querySelector('#masterBody').textContent,'');dom.window.close();});
test('published history opens the actual project and locks republishing',async()=>{const {w,dom}=app();await w.openProject('demo-history');assert.match(w.document.querySelector('#detailBody').textContent,/Completed/);assert.equal(w.document.querySelector('#detailBody button[onclick^="publishEtsy"]').disabled,true);dom.window.close();});
test('editor has 13 individual tag inputs and independent field selectors',()=>{const {w,dom}=app();w.openEdit('demo-edit');assert.equal(w.document.querySelectorAll('input[name^="tag_"]').length,13);for(const key of ['title','description','price','tags'])assert.ok(w.document.querySelector('[name="scope_'+key+'"]'));assert.ok(w.document.querySelector('[name="replace_700000001"]'));assert.ok(w.document.querySelector('[name="add_files"]'));dom.window.close();});
test('saving title only keeps description, price and tags unselected',async()=>{const {w,dom,calls}=app();w.openEdit('demo-edit');w.document.querySelector('[name="field_title"]').value='Changed Sample Title';await w.saveEdit({preventDefault(){},currentTarget:w.document.querySelector('#editForm')});const body=w.document.querySelector('#detailBody');assert.match(body.textContent,/Changed Sample Title/);assert.equal(body.querySelectorAll('.compare').length,1);assert.equal(calls(),0);dom.window.close();});
test('archive and revision restore retain the sample project',async()=>{const {w,dom}=app();await w.clearProject('demo-edit');await w.openProject('demo-edit');assert.match(w.document.querySelector('#detailBody').textContent,/Restore archive/);await w.clearProject('demo-edit');await w.restoreRevision('demo-edit',1);assert.match(w.document.querySelector('#detailBody').textContent,/Select at least one change/);dom.window.close();});
test('Pinterest clearly offers manual posting rather than fake publishing',()=>{const {w,dom}=app();const text=w.document.querySelector('#pinterestList').textContent;assert.match(text,/Automatic Pinterest publishing is unavailable/);assert.match(text,/Plan Posting/);assert.doesNotMatch(text,/Post now|sent for publishing/);dom.window.close();});
