const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),vm=require('node:vm');const {stripTypeScriptTypes}=require('node:module');
function setup({unauthorised=false,notOwner=false,timeout=false,mismatch=false}={}){
 let handler,posts=0;const project={id:'project',kind:'pinterest',status:'ready',revision:1,manifest:{pins:[{boardId:'123',link:'https://www.etsy.com/listing/456',title:'Planner pin',description:'Travel guide',imageRole:'pin-1'}]},media:[{role:'pin-1',path:'owner/project/pin.png'}]};
 const admin={auth:{getUser:async()=>({data:{user:unauthorised?null:{id:'owner'}}})},storage:{from:()=>({download:async()=>({data:new Blob([new Uint8Array([137,80,78,71])],{type:'image/png'})})})},from(table){const q={filters:[],changes:null,select(){return q},eq(k,v){q.filters.push([k,v]);return q},update(v){q.changes=v;return q},single:async()=>q.run(),maybeSingle:async()=>q.run(),then(a,b){return Promise.resolve(q.run()).then(a,b)},run(){if(table==='app_owners')return {data:notOwner?null:{user_id:'owner'}};assert.equal(table,'review_projects');if(!q.filters.every(([k,v])=>project[k]===v))return {data:null};if(q.changes)Object.assign(project,structuredClone(q.changes));return {data:structuredClone(project)};}};return q;}};
 const ctx=vm.createContext({Request,Response,Blob,Uint8Array,crypto,btoa,Date,AbortSignal,createClient:()=>admin,listBoards:async()=>[{id:'123'}],pinterestRequest:async(path,init)=>{if(init.method==='POST'){posts++;if(timeout)throw Error('network lost');return {id:'789'};}return {id:'789',board_id:'123',link:project.manifest.pins[0].link,title:mismatch?'Wrong':project.manifest.pins[0].title,description:'Travel guide'};},Deno:{env:{get:()=> 'test'},serve:fn=>handler=fn}});
 vm.runInContext(stripTypeScriptTypes(fs.readFileSync('supabase/functions/pinterest-publish/index.ts','utf8').replace(/^import .*?;\s*$/gm,'')),ctx);
 return {project,posts:()=>posts,run:async()=>{const r=await handler(new Request('https://example.test',{method:'POST',headers:{authorization:'Bearer test'},body:JSON.stringify({project_id:'project',expected_revision:1})}));return {status:r.status,data:await r.json()};}};
}
test('Pinterest posting requires an authenticated owner',async()=>{for(const options of [{unauthorised:true},{notOwner:true}]){const s=setup(options);assert.ok((await s.run()).status>=400);assert.equal(s.posts(),0);}});
test('approved pin is read back before being marked published',async()=>{const s=setup();assert.equal((await s.run()).data.verified,true);assert.equal(s.project.status,'published');await s.run();assert.equal(s.posts(),1);});
test('uncertain Pinterest response cannot create a duplicate pin on retry',async()=>{const s=setup({timeout:true});assert.equal((await s.run()).status,400);assert.equal(s.project.status,'failed');await s.run();assert.equal(s.posts(),1);});
test('incorrect Pinterest readback is retained for review',async()=>{const s=setup({mismatch:true});assert.equal((await s.run()).status,400);assert.equal(s.project.status,'failed');assert.equal(s.project.platform_id,'789');});
test('changed review revision blocks Pinterest before a platform write',async()=>{const s=setup();s.project.revision=2;assert.equal((await s.run()).status,400);assert.equal(s.posts(),0);});
