const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
const base=require('node:path').join(__dirname,'../supabase/functions/etsy-publish');
const context=vm.createContext({TextDecoder,TextEncoder,Blob,FormData,URLSearchParams,Headers,Response,Request,AbortSignal,crypto,structuredClone,Date,console});
function load(name){return stripTypeScriptTypes(fs.readFileSync(base+'/'+name,'utf8').replace(/^import .*?;\s*$/gm,'').replace(/\bexport /g,''));}
vm.runInContext(load('assets.ts')+'\n'+load('safety.ts')+'\n'+load('safe-edit.ts')+'\n'+load('reconcile-edit.ts'),context);
const {runEdit,preflightFiles,verifyFields}=context;
const source=fs.readFileSync(base+'/index.ts','utf8');
vm.runInContext(stripTypeScriptTypes(source.slice(source.indexOf('function numberValue('),source.indexOf('async function etsyFetch('))),context);
function setup({count=2,uploadFail=false,drift=false,unexpectedField=false}={}){
 const files=Array.from({length:count},(_,i)=>({listing_file_id:String(100+i),rank:i+1,filename:`file${i}.pdf`}));
 const original={user_id:'owner',title:'Old title',description:'Original copy',price:{amount:1499,divisor:100},tags:['one'],images:[]};
 const current=structuredClone(original),runs=[],writes=[];
 const project={id:'project',kind:'etsy',title:'Sample',revision:1,status:'ready',media:[{role:'pdf',path:'safe/path',name:'new.pdf'}],manifest:{mode:'edit',listingId:'12345',updateScope:['files'],updateFields:{},fileUpdates:[{action:'replace',listingFileId:'100',role:'pdf',filename:'new.pdf'}]}};
 const admin={from(table){const q={changes:null,filters:[],insert:async value=>{if(table==='seller_publish_runs'&&runs.some(r=>r.listing_key===value.listing_key&&['running','needs_review'].includes(r.status)))return {error:Error('duplicate')};runs.push({...structuredClone(value)});return {error:null};},update(v){this.changes=structuredClone(v);return this;},eq(k,v){this.filters.push([k,v]);return this;},in(k,v){this.filters.push([k,v]);return this;},select(){return this;},order(){return this;},limit(){return this;},maybeSingle(){return Promise.resolve(this.apply());},then(resolve,reject){return Promise.resolve(this.apply()).then(resolve,reject);},apply(){const rows=table==='seller_publish_runs'?runs:[project];const matches=rows.filter(r=>this.filters.every(([k,v])=>Array.isArray(v)?v.includes(r[k]):r[k]===v));matches.forEach(r=>Object.assign(r,this.changes));return {data:matches[0]?structuredClone(matches[0]):null,error:null};}};return q;}};
 const api={fetch:async(path,token,init)=>{if(init?.method==='DELETE'){writes.push('delete');const i=files.findIndex(x=>String(x.listing_file_id)===path.split('/').at(-1));files.splice(i,1);return {};}if(path.endsWith('/images'))return {results:structuredClone(current.images)};if(path.endsWith('/files'))return {results:structuredClone(files)};if(drift)current.title='Externally edited';return structuredClone(current);},storageFile:async()=>new Blob(['%PDF-1.7 content']),uploadFile:async()=>{writes.push('upload');if(uploadFail)throw Error('upload timeout');const file={listing_file_id:'200',rank:1,filename:'new.pdf'};files.push(file);return file;},updateFields:async(shop,id,token,fields)=>{writes.push('fields');Object.assign(current,fields);if(unexpectedField)current.description='Unexpected mutation';},uploadImage:async()=>{writes.push('image');},altText:async()=>{writes.push('alt');},personalization:async()=>{writes.push('personalization');}};
 const listing=()=>context.validateProject(project);
 return {project,runs,writes,files,current,admin,api,listing,run:()=>runEdit(admin,{shop_id:'shop',etsy_user_id:'owner'},'test',project,listing(),api)};
}
test('unsupported edit fields are rejected before publishing',()=>{for(const key of ['price','tags','alt_text','quantity']){const s=setup();s.project.manifest.updateScope=[key];s.project.manifest.updateFields={[key]:'value'};assert.throws(()=>s.listing(),/unsupported/);}});
test('replacement uploads before deleting original and verifies the exact file set',async()=>{const s=setup();const result=await s.run();assert.equal(result.verified,true);assert.deepEqual(s.writes,['upload','delete']);assert.deepEqual(s.files.map(x=>x.listing_file_id).sort(),['101','200']);assert.equal(s.runs[0].status,'succeeded');});
test('full five-file listing is blocked before any Etsy write',async()=>{const s=setup({count:5});await assert.rejects(s.run(),/one free Etsy file slot/);assert.deepEqual(s.writes,[]);assert.equal(s.files.length,5);assert.equal(s.runs[0].status,'blocked');});
test('upload failure retains original and blocks unsafe retry',async()=>{const s=setup({uploadFail:true});await assert.rejects(s.run(),/may already be live/);assert.deepEqual(s.writes,['upload']);assert.equal(s.files[0].listing_file_id,'100');assert.equal(s.runs[0].status,'needs_review');await assert.rejects(s.run(),/unresolved update/);assert.deepEqual(s.writes,['upload']);});
test('parallel attempts cannot publish the same listing twice',async()=>{const s=setup();const result=await Promise.allSettled([s.run(),s.run()]);assert.equal(result.filter(x=>x.status==='fulfilled').length,1);assert.equal(result.filter(x=>x.status==='rejected').length,1);assert.deepEqual(s.writes,['upload','delete']);});
test('stale draft is blocked before changing Etsy',async()=>{const s=setup({drift:true});s.project.manifest.existingSnapshot={title:'Old title'};await assert.rejects(s.run(),/changed since this draft/);assert.deepEqual(s.writes,[]);});
test('an unexpected change to an omitted field is reported as requiring review',async()=>{const s=setup({unexpectedField:true});s.project.manifest.updateScope=['title'];s.project.manifest.updateFields={title:'New title'};await assert.rejects(s.run(),/description differs/);assert.equal(s.runs[0].status,'needs_review');});
test('duplicate file targets and excess additions fail preflight',()=>{assert.throws(()=>preflightFiles([{listing_file_id:'1'}],[{action:'replace',listingFileId:'1'},{action:'replace',listingFileId:'1'}]),/only once/);assert.throws(()=>preflightFiles(Array(5).fill({}),[{action:'add'}]),/five digital files/);});
test('archived and publishing projects cannot be submitted',()=>{const s=setup();s.project.status='publishing';assert.throws(()=>s.listing(),/already|another request/);s.project.status='ready';s.project.manifest.archived=true;assert.throws(()=>s.listing(),/archived/);});

test('empty optional styles and materials do not falsely block a PDF-only replacement',async()=>{for(const value of [undefined,null,[]]){const s=setup();s.current.styles=value;s.current.materials=value;s.project.manifest.existingSnapshot={styles:[],materials:[]};await s.run();assert.deepEqual(s.writes,['upload','delete']);}});
test('real styles changes still block before any Etsy writes',async()=>{const s=setup();s.current.styles=['Modern'];s.project.manifest.existingSnapshot={styles:[]};await assert.rejects(s.run(),/live styles changed/);assert.deepEqual(s.writes,[]);});
test('draft preparation and publishing use the same snapshot function',()=>{assert.match(source,/existingSnapshot:listingSnapshot\(existing\)/);const snap=context.listingSnapshot({styles:null,materials:undefined,tags:[],price:{amount:1499,divisor:100}});assert.equal(snap.price,14.99);assert.deepEqual(JSON.parse(JSON.stringify(snap.styles)),[]);});

function imageSetup(){const s=setup();s.api.storageFile=async()=>new Blob([new Uint8Array([137,80,78,71,...Array(20).fill(0)])]);s.current.images=[{listing_image_id:'10',rank:1,alt_text:'Old alt'}];s.project.manifest.updateScope=['images'];s.project.manifest.imageReplacements=[{role:'listing-image-1',rank:1,altText:'Approved alt'}];s.project.media=[{role:'listing-image-1',path:'image/path',name:'new.png'}];s.api.uploadImage=async()=>{s.writes.push('image');s.current.images[0].listing_image_id='20';s.current.images[0].alt_text='Approved alt';return {...s.current.images[0]};};s.api.altText=async(shop,id,token,image)=>{s.writes.push('alt');assert.equal(String(image.listingImageId),'20');s.current.images[0].alt_text=image.altText;return {...s.current.images[0]};};return s;}
test('replacement sends one image request and verifies its matching alt text',async()=>{const s=imageSetup();await s.run();assert.deepEqual(s.writes,['image']);assert.equal(s.runs[0].steps[0].image_id,'20');assert.equal(s.current.images[0].alt_text,'Approved alt');});
test('failed alt verification retains readback and blocks duplicate uploads',async()=>{const s=imageSetup();s.api.uploadImage=async()=>{s.writes.push('image');s.current.images[0].listing_image_id='20';return {listing_image_id:'20'};};await assert.rejects(s.run(),/Image 1 verification/);assert.equal(s.runs[0].after_state.images[0].alt_text,'Old alt');await assert.rejects(s.run(),/unresolved/);assert.deepEqual(s.writes,['image']);});
test('wrong returned image identity cannot pass even with matching alt text',async()=>{const s=imageSetup();s.api.uploadImage=async()=>{s.writes.push('image');return {listing_image_id:'20'};};await assert.rejects(s.run(),/Image 1 verification/);assert.equal(s.runs[0].status,'needs_review');});
test('non-PDF bytes are rejected before any Etsy write',async()=>{const s=setup();s.api.storageFile=async()=>new Blob(['not a PDF']);await assert.rejects(s.run(),/genuine PDFs/);assert.deepEqual(s.writes,[]);});
test('unsupported image formats are rejected before any Etsy write',async()=>{const s=imageSetup();s.api.storageFile=async()=>new Blob(['RIFF webp']);await assert.rejects(s.run(),/PNG or JPEG/);assert.deepEqual(s.writes,[]);});
test('overlong replacement alt text is rejected rather than silently truncated',()=>{const s=imageSetup();s.project.manifest.imageReplacements[0].altText='a'.repeat(501);assert.throws(()=>s.listing(),/alt text/);});
test('image position 20 is accepted and position 21 rejected',()=>{const s=imageSetup();s.project.manifest.imageReplacements[0].rank=20;assert.equal(s.listing().images[0].rank,20);s.project.manifest.imageReplacements[0].rank=21;assert.throws(()=>s.listing(),/rank/);});
test('new listing asset verification rejects missing, reordered or wrong-alt images and wrong PDF',()=>{const images=Array.from({length:6},(_,i)=>({rank:i+1,listing_image_id:String(i+10),alt_text:`Alt ${i}`}));const checkpoint={imageIds:images.map(x=>x.listing_image_id),fileId:'55'},alt=images.map(x=>x.alt_text),files=[{listing_file_id:'55'}];context.verifyNewListingAssets({images},files,checkpoint,alt);for(const change of [x=>x.pop(),x=>x[3].alt_text='old',x=>x[3].listing_image_id='999',x=>x[3].rank=6]){const bad=structuredClone(images);change(bad);assert.throws(()=>context.verifyNewListingAssets({images:bad},files,checkpoint,alt),/not been activated/);}assert.throws(()=>context.verifyNewListingAssets({images},[{listing_file_id:'wrong'}],checkpoint,alt),/PDF/);});
test('invalid or overprecise price cannot cause a partial listing update',()=>{for(const price of [Infinity,NaN,0,-1,1.999]){const s=setup();s.project.manifest.updateScope=['price'];s.project.manifest.updateFields={price};assert.throws(()=>s.listing(),/unsupported/);}});
test('each requested text field is independent and leaves images and files untouched',async()=>{for(const [key,value] of Object.entries({title:'New title',description:'New description'})){const s=setup();const oldFiles=JSON.stringify(s.files);s.project.manifest.updateScope=[key];s.project.manifest.updateFields={[key]:value};await s.run();assert.deepEqual(s.writes,['fields']);assert.equal(JSON.stringify(s.files),oldFiles);assert.deepEqual(s.current[key],value);}});
test('an externally replaced selected image blocks before writes',async()=>{const s=imageSetup();s.project.manifest.existingImages=[{id:'9',rank:1}];await assert.rejects(s.run(),/changed since this draft/);assert.deepEqual(s.writes,[]);});
test('unexpected additional image is not mistaken for a successful replacement',async()=>{const s=imageSetup();const upload=s.api.uploadImage;s.api.uploadImage=async(...args)=>{const result=await upload(...args);s.current.images.push({listing_image_id:'30',rank:2,alt_text:'Unexpected'});return result;};await assert.rejects(s.run(),/Image count or order/);assert.equal(s.runs[0].status,'needs_review');});
test('a gap in new image positions blocks before any Etsy write',async()=>{const s=imageSetup();s.project.manifest.imageReplacements[0].rank=20;await assert.rejects(s.run(),/consecutive/);assert.deepEqual(s.writes,[]);});

test('delayed Etsy image readback can reconcile without another image upload',async()=>{const s=imageSetup();s.project.manifest.fileUpdates=[];s.api.uploadImage=async()=>{s.writes.push('image');s.current.images[0].listing_image_id='20';return {listing_image_id:'20'};};await assert.rejects(s.run());s.current.images[0].alt_text='Approved alt';const checked=await context.reconcileEdit(s.admin,{shop_id:'shop',etsy_user_id:'owner'},'test',s.project,s.api);assert.equal(checked.verified,true);assert.equal(s.project.status,'published');assert.deepEqual(s.writes,['image']);});
test('reconciliation retains a mismatch without changing Etsy',async()=>{const s=imageSetup();s.project.manifest.fileUpdates=[];s.api.uploadImage=async()=>{s.writes.push('image');s.current.images[0].listing_image_id='20';return {listing_image_id:'20'};};await assert.rejects(s.run());const checked=await context.reconcileEdit(s.admin,{shop_id:'shop',etsy_user_id:'owner'},'test',s.project,s.api);assert.equal(checked.verified,false);assert.equal(s.project.status,'failed');assert.ok(s.runs[0].after_state.checked_at);assert.deepEqual(s.writes,['image']);});
