const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM}=require('jsdom');
function studio(projects=[]){
 const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://example.test/',runScripts:'outside-only'});
 const w=dom.window;let auth;
 const client={auth:{onAuthStateChange:fn=>auth=fn},from:()=>({select:()=>({in:()=>({order:async()=>({data:projects})})})})};
 w.supabase={createClient:()=>client};w.structuredClone=structuredClone;w.AbortSignal=AbortSignal;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 const vm=require('node:vm'); new vm.Script(fs.readFileSync('studio.js','utf8')).runInContext(dom.getInternalVMContext());
 return {w,dom,auth,run:code=>new vm.Script(code).runInContext(dom.getInternalVMContext())};
}
test('exactly three bottom tabs in the agreed order and Editing is the default',()=>{const {w,dom}=studio();assert.deepEqual([...w.document.querySelectorAll('nav button')].map(x=>x.textContent),['Editing','Posting','Storage']);assert.equal(w.document.querySelector('[aria-current=page]').dataset.tab,'editing');assert.equal(w.document.querySelectorAll('script[src*=workspace]').length,0);dom.window.close();});
test('signed-out storage and review contents are removed',()=>{const {w,auth,dom}=studio();w.document.querySelector('#content').textContent='private content';auth('SIGNED_OUT',null);assert.equal(w.document.querySelector('#content').textContent,'');assert.equal(w.document.querySelector('#workspace').hidden,true);assert.equal(w.document.querySelector('#navigation').hidden,true);dom.window.close();});
test('untrusted content is escaped and unsafe preview URLs are rejected',()=>{const {run,dom}=studio();assert.equal(run("safeUrl('javascript:alert(1)')"),'');assert.equal(run("safeUrl('https://www.etsy.com/listing/123')"),'https://www.etsy.com/listing/123');assert.equal(run("escapeHtml('<img onerror=alert(1)>')"),'&lt;img onerror=alert(1)&gt;');dom.window.close();});
test('failed publication cannot be retried blindly from the approval preview',()=>{const {w,run,dom}=studio();run(`state.connections=[{platform:'etsy',status:'connected'}];state.projects=[{id:'example',title:'Planner',status:'failed',kind:'etsy',manifest:{mode:'edit',updateFields:{title:'New title'},existingSnapshot:{title:'Old title'},updateScope:['title']}}];openReview('example');`);assert.equal(w.document.querySelector('[data-approve]').disabled,true);assert.match(w.document.querySelector('#review-content').textContent,/Old title/);assert.match(w.document.querySelector('#review-content').textContent,/New title/);dom.window.close();});
test('storage renders only the current Word file and no old image or PDF controls',()=>{const {w,run,dom}=studio();run(`state.masters=[{id:'example',title:'Planner',files:[{role:'docx',name:'Current.docx'},{role:'pdf',name:'Private.pdf'},{role:'thumbnail',name:'Image.jpg'}]}];renderStorage();`);const text=w.document.querySelector('#content').textContent;assert.match(text,/Current.docx/);assert.doesNotMatch(text,/Private.pdf|Image.jpg|history|revision/i);assert.equal(w.document.querySelector('input[type=file]').accept,'.docx');dom.window.close();});
test('failed image review offers guarded completion while ordinary approval stays disabled',()=>{const {w,run,dom}=studio();run(`state.connections=[{platform:'etsy',status:'connected'}];state.projects=[{id:'example',title:'Planner',status:'failed',kind:'etsy',manifest:{mode:'edit',updateFields:{},updateScope:['images'],imageReplacements:[]}}];openReview('example');`);assert.equal(w.document.querySelector('[data-approve]').disabled,true);assert.equal(w.document.querySelector('[data-resume-images]').textContent,'Finish approved image update');dom.window.close();});

test('blueprint is first and exposes the same current DOCX controls',()=>{const {w,run,dom}=studio();run(`state.masters=[{id:'planner',category:'planner',title:'Japan',files:[]},{id:'blueprint',category:'blueprint',title:'Planner & Listing Blueprint',files:[{role:'docx',name:'Blueprint.docx'}]}];renderStorage();`);const first=w.document.querySelector('.storage-row');assert.match(first.textContent,/Blueprint.docx/);for(const action of ['download','upload','delete'])assert.equal(first.querySelector('[data-'+action+']').dataset[action],'blueprint');dom.window.close();});
test('empty blueprint slot remains available above planners',()=>{const {w,run,dom}=studio();run(`state.masters=[];renderStorage();`);assert.equal(w.document.querySelector('[data-upload]').dataset.upload,'blueprint-new');assert.equal(w.document.querySelector('#content input').accept,'.docx');dom.window.close();});
test('file picker survives focus and auth refresh, supports selection and same-file retry',async()=>{const {w,run,auth,dom}=studio();run(`state.session={user:{id:'owner'}};state.tab='storage';state.masters=[{id:'blueprint',category:'blueprint',title:'Blueprint',files:[]}];renderStorage();globalThis.received=[];upload=async(id,file)=>{received.push([id,file.name]);render();};`);w.document.querySelector('[data-upload]').click();const input=w.document.querySelector('#file-blueprint');assert.equal(input.parentNode,w.document.body);w.location.hash='storage';w.dispatchEvent(new w.Event('focus'));auth('SIGNED_IN',{user:{id:'owner'}});await new Promise(r=>setTimeout(r,5));assert.equal(w.document.querySelector('#file-blueprint'),input);Object.defineProperty(input,'files',{value:[new w.File(['docx'],'Blueprint.docx')]});input.dispatchEvent(new w.Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,0));assert.equal(run('received.length'),1);assert.equal(run('state.pickingFile'),false);w.document.querySelector('[data-upload]').click();const retry=w.document.querySelector('#file-blueprint');assert.notEqual(retry,input);retry.dispatchEvent(new w.Event('cancel'));assert.equal(run('state.pickingFile'),false);dom.window.close();});
test('release check uses displayed version and suppresses reload during file selection',async()=>{const {w,run,dom}=studio();w.fetch=async()=>({ok:true,json:async()=>({app_version:37})});assert.equal(run('APP_VERSION'),37);await run('checkRelease()');assert.doesNotMatch(fs.readFileSync('studio.js','utf8'),/release.app_version>36/);assert.match(fs.readFileSync('studio.js','utf8'),/release.app_version>APP_VERSION.*!state.pickingFile/);dom.window.close();});
