import {test} from 'node:test';import assert from 'node:assert/strict';
import {handleComposer,composerTools} from '../../supabase/functions/composer/actions.ts';
const owner='owner',planner='10000000-0000-4000-8000-000000000001',background='10000000-0000-4000-8000-000000000002',page='10000000-0000-4000-8000-000000000003';
const spec={planner_id:planner,background_id:background,output_type:'square',font_family:'Lora',composition_profile:'balanced_premium',headline:'Your next escape',planner_page_ids:[page],layout_preset:'proof_right'};
function setup(){
 const db={composer_compositions:[],composer_revisions:[],composer_assets:[{id:background,user_id:owner,planner_id:planner,kind:'background',width:1080,height:1080,ready:true,path:'background',metadata:{}},{id:page,user_id:owner,planner_id:planner,kind:'page',width:1414,height:2000,source_checksum:'current',ready:true,path:'page'}],seller_master_records:[{id:planner,user_id:owner,files:[{role:'docx',checksum:'current'}]}]};let removed=[];
 const admin={from(table){assert.ok(table.startsWith('composer_')||table==='seller_master_records','Unrelated table accessed');let filters=[],operation='read',value,single=false,limit;const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},neq(k,v){filters.push(r=>r[k]!==v);return q},in(k,v){filters.push(r=>v.includes(r[k]));return q},or(filter){const m=filter.match(/width.eq.(\d+),height.eq.(\d+)/);assert.ok(m);filters.push(r=>r.kind==='page'||r.kind==='background'&&r.width===Number(m[1])&&r.height===Number(m[2]));return q},order(){return q},range(a,b){limit=[a,b];return q},ilike(){return q},insert(v){value=v;operation='insert';return q},update(v){value=v;operation='update';return q},upsert(v){value=v;operation='upsert';return q},delete(){operation='delete';return q},single(){single=true;return q},maybeSingle(){single=true;return q},then(resolve,reject){try{let rows=db[table].filter(r=>filters.every(f=>f(r)));if(operation==='insert'){const r={id:crypto.randomUUID(),revision:1,status:'draft',result:null,...structuredClone(value)};db[table].push(r);rows=[r];}if(operation==='update')rows.forEach(r=>Object.assign(r,structuredClone(value)));if(operation==='upsert'){db[table].push(structuredClone(value));rows=[value];}if(operation==='delete')db[table]=db[table].filter(r=>!rows.includes(r));const count=rows.length;if(limit)rows=rows.slice(limit[0],limit[1]+1);resolve({data:structuredClone(single?rows[0]??null:rows),count});}catch(e){reject(e)}}};return q;},storage:{from(bucket){assert.equal(bucket,'composer-private');return {createSignedUrl:async p=>({data:{signedUrl:'https://private.test/'+p}}),remove:async p=>{removed.push(...p);return {data:[]}}};}}};
 return {db,removed,call:(n,args)=>handleComposer(n,args,{admin,userId:owner})};
}
test('create retries retain identity, changed content needs a new request key, and owners are isolated',async()=>{const h=setup();const args={composition:spec,idempotency_key:'qa-retry-key'};const a=await h.call('create_marketing_composition',args),b=await h.call('create_marketing_composition',args);assert.equal(a.composition_id,b.composition_id);assert.equal(h.db.composer_compositions.length,1);await assert.rejects(h.call('create_marketing_composition',{...args,composition:{...spec,headline:'Changed'}}),/Idempotency/);h.db.composer_assets[0].user_id='another';await assert.rejects(h.call('create_marketing_composition',{...args,idempotency_key:'different-key'}),/unverified/);});
test('source replacement invalidates page use and rendering without modifying the source',async()=>{const h=setup();h.db.seller_master_records[0].files[0].checksum='new';await assert.rejects(h.call('create_marketing_composition',{composition:spec,idempotency_key:'stale-page-key'}),/STALE_SOURCE/);assert.equal(h.db.composer_compositions.length,0);});
test('batch queues valid items independently, update invalidates output, stale revisions fail',async()=>{const h=setup(),a=await h.call('create_marketing_composition',{composition:spec,idempotency_key:'batch-test-key'});const results=await h.call('render_marketing_composition',{items:[{composition_id:'missing',expected_revision:1},{composition_id:a.composition_id,expected_revision:1}]});assert.ok(results.results[0].error);assert.equal(results.results[1].status,'queued');const u=await h.call('update_marketing_composition',{composition_id:a.composition_id,expected_revision:1,composition:{...spec,headline:'A new journey'}});assert.equal(u.revision,2);assert.equal(u.status,'draft');await assert.rejects(h.call('update_marketing_composition',{composition_id:a.composition_id,expected_revision:1,composition:spec}),/Revision conflict/);});
test('export requires a verified current preview, cancellation only removes that composition outputs',async()=>{const h=setup(),a=await h.call('create_marketing_composition',{composition:spec,idempotency_key:'export-test-key'});const args={composition_id:a.composition_id,expected_revision:1,confirmed:true};await assert.rejects(h.call('export_marketing_composition',args),/validated rendered/);h.db.composer_compositions[0].status='ready';h.db.composer_compositions[0].result={path:'only-this-output',checksum:'rendered',validation:{valid:true}};assert.equal((await h.call('export_marketing_composition',args)).published,false);await h.call('delete_marketing_composition',args);assert.deepEqual(h.removed,['only-this-output']);assert.equal(h.db.composer_assets.length,2);assert.equal(h.db.seller_master_records[0].files[0].checksum,'current');});
test('schemas expose twenty-four narrow private actions and no publication action',()=>{assert.equal(composerTools.length,24);for(const t of composerTools){assert.equal(t.inputSchema.additionalProperties,false);assert.equal(t.annotations.openWorldHint,false);assert.doesNotMatch(t.name,/publish|pinterest|etsy/);}});

test('catalogue defaults to square and selects portrait backgrounds while retaining genuine pages',async()=>{const h=setup();h.db.composer_assets.push({...h.db.composer_assets[0],id:'portrait-background',width:1000,height:1500});const square=await h.call('get_composer_catalog',{}),portrait=await h.call('get_composer_catalog',{output_type:'pinterest'});assert.deepEqual(square.assets.map(a=>a.id),[background,page]);assert.deepEqual(portrait.assets.map(a=>a.id),[page,'portrait-background']);assert.deepEqual(portrait.dimensions,{width:1000,height:1500});await assert.rejects(h.call('get_composer_catalog',{output_type:'arbitrary'}),/Unsupported output/);});
