import {test} from 'node:test';import assert from 'node:assert/strict';import sharp from 'sharp';import {unzipSync} from 'fflate';
import {createRendererSession,sha} from '../renderer.mjs';import {zipPngs,inspectPng} from '../../supabase/functions/composer/archive.mjs';
import {wakeRenderer} from '../../supabase/functions/composer/dispatch.ts';import {campaignTimings} from '../../supabase/functions/composer/campaigns.ts';
import {handleCampaign} from '../../supabase/functions/composer/campaigns.ts';import {canonical,hash} from '../../supabase/functions/composer/core.mjs';
const png=await sharp({create:{width:1080,height:1080,channels:3,background:'#142C35'}}).png().toBuffer();
const bg={id:'10000000-0000-4000-8000-000000000002',planner_id:'10000000-0000-4000-8000-000000000001',kind:'background',width:1080,height:1080,checksum:sha(png),metadata:{}};
const spec={planner_id:bg.planner_id,background_id:bg.id,output_type:'square',font_family:'Lora',composition_profile:'balanced_premium',headline:'One Christmas trip.',supporting_copy:'A thoughtful route for your next adventure.',planner_page_ids:[],layout_preset:'editorial_hook'};
test('actual-font preflight preserves wording and resolves isolated last words before loading images',async()=>{const s=await createRendererSession();try{const r=await s.preflight(spec,[bg]);assert.equal(r.preflight.exact_text,true);assert.ok(r.preflight.lines.find(x=>x.name==='headline').original_isolated_words.some(x=>x.word==='trip.'));assert.ok(r.preflight.lines.every(x=>!x.isolated_words.length));assert.equal(s.statistics.asset_cache_misses,0);assert.ok(r.preflight.lines.every(x=>x.font_size>=({headline:56,supporting_copy:32})[x.name]));assert.equal(r.preflight.lines.find(x=>x.name==='headline').text,spec.headline);}finally{await s.close();}});
test('shared browser renders concurrently with identical bytes and a verified per-owner asset cache',async()=>{const s=await createRendererSession();let loads=0;try{const load=async()=>{loads++;return png;};const a=await Promise.all([1,2,3].map(()=>s.render(spec,[bg],load,{scope:'one-owner'})));assert.equal(new Set(a.map(x=>x.checksum)).size,1);assert.equal(loads,1);assert.equal(s.statistics.browser_starts,1);await s.render(spec,[bg],load,{scope:'another-owner'});assert.equal(loads,2);assert.ok(a.every(x=>x.validation.full_decode));}finally{await s.close();}});
test('incomplete or modified PNG framing is rejected even if a supplied whole-file checksum matches',async()=>{assert.throws(()=>inspectPng(png.subarray(0,png.length-12)),/Incomplete/);const b=Buffer.from(png);b[50]^=1;assert.throws(()=>inspectPng(b),/checksum/);const s=await createRendererSession();try{const truncated=png.subarray(0,png.length-12);await assert.rejects(s.render(spec,[{...bg,checksum:sha(truncated)}],async()=>truncated),/Incomplete/);}finally{await s.close();}});
test('ZIP contains exactly five numbered intact PNGs and is reproducible',()=>{const files=Array.from({length:5},(_,i)=>({name:`campaign_slide_0${i+1}.png`,bytes:png})),zip=zipPngs(files),opened=unzipSync(zip);assert.deepEqual(Object.keys(opened),files.map(x=>x.name));assert.ok(files.every(f=>sha(opened[f.name])===sha(f.bytes)));assert.equal(sha(zip),sha(zipPngs(files)));assert.throws(()=>zipPngs(files.slice(1)),/five/);assert.throws(()=>zipPngs(files.map((x,i)=>i?x:{...x,name:'../unsafe.png'})),/Unsafe/);});
test('dispatch uses only the fixed renderer, keeps secrets out of payloads, and reports fallback honestly',async()=>{let req;const r=await wakeRenderer({token:'private-test-token',fetcher:async(url,args)=>{req={url,args};return {ok:true};}});assert.equal(r.immediate_start,true);assert.match(req.url,/Pinterest-Scheduler\/actions\/workflows\/composer-render.yml\/dispatches$/);assert.equal(req.args.body,'{"ref":"main"}');assert.ok(!JSON.stringify(r).includes('private-test-token'));assert.equal((await wakeRenderer({token:'',fetcher:()=>assert.fail()})).reason,'DISPATCH_CREDENTIAL_NOT_CONFIGURED');assert.equal((await wakeRenderer({token:'x',fetcher:async()=>({ok:false,status:403})})).mode,'scheduled_backup');});
test('timings separate first pass, corrected completion, preparation and overlapping per-slide work',()=>{const zero='2026-09-12T10:00:00Z',rows=Array.from({length:5},(_,i)=>({id:String(i),slide_number:i+1,revision:i?1:2,status:'ready',queued_at:zero,started_at:'2026-09-12T10:00:01Z',completed_at:'2026-09-12T10:00:20Z',timings:{rendering_ms:500}})),attempts=rows.map((r,i)=>({composition_id:r.id,revision:1,job_kind:'render',started_at:zero,completed_at:'2026-09-12T10:00:10Z',status:i?'ready':'validation_failed'}));const t=campaignTimings({first_submitted_at:zero,preparation_started_at:'2026-09-12T09:59:00Z'},rows,attempts);assert.equal(t.preparation_seconds,60);assert.equal(t.first_pass.successful,false);assert.equal(t.first_pass.seconds,10);assert.equal(t.after_corrections.seconds,20);assert.equal(t.after_corrections.changed_slide_count,1);assert.equal(t.slides[0].queue_wait_ms,1000);});

function campaignFixture(){
 const camp={id:'campaign',user_id:'owner',planner_id:bg.planner_id,title:'Private campaign',revision:2,status:'submitted',source:{}};
 const rows=Array.from({length:5},(_,i)=>({id:`slide-${i}`,campaign_id:camp.id,user_id:'owner',slide_number:i+1,revision:1,status:'ready',spec,result:{path:`slide-${i}.png`,checksum:sha(png),validation:{valid:true}}}));
 const db={composer_campaigns:[camp],composer_compositions:rows,composer_render_attempts:[],composer_campaign_requests:[]};const objects=new Map(rows.map(c=>[c.result.path,png]));let uploads=0,approved=0,woken=0;
 const admin={from(t){assert.ok(t.startsWith('composer_'));let fs=[],one=false;const q={select(){return q},eq(k,v){fs.push(r=>r[k]===v);return q},neq(k,v){fs.push(r=>r[k]!==v);return q},in(k,v){fs.push(r=>v.includes(r[k]));return q},order(){return q},limit(){return q},maybeSingle(){one=true;return q},then(resolve){const found=db[t].filter(r=>fs.every(f=>f(r)));resolve({data:structuredClone(one?found[0]||null:found)})}};return q},storage:{from(b){assert.equal(b,'composer-private');return {createSignedUrl:async p=>({data:{signedUrl:'https://private.invalid/'+p}}),download:async p=>({data:new Blob([objects.get(p)])}),upload:async(p,b)=>{uploads++;objects.set(p,b);return {data:{}}},remove:async paths=>{paths.forEach(p=>objects.delete(p));return {data:{}}}}}},rpc:async(name,args)=>{assert.equal(name,'composer_approve_campaign');approved++;camp.export_bundle=args.p_bundle;return {data:{approved:true,bundle:args.p_bundle}}}};
 return {camp,rows,db,objects,get uploads(){return uploads},get approved(){return approved},get woken(){return woken},call:(name,args)=>handleCampaign(name,args,{admin,userId:'owner',selectedAssets:async()=>[bg],wake:async()=>{woken++;return {immediate_start:true}}})};
}
test('batch review binds the five exact previews; stale approval cannot upload or approve',async()=>{const h=campaignFixture(),review=await h.call('get_marketing_campaign',{campaign_id:'campaign'});assert.equal(review.slides.length,5);assert.ok(review.slides.every(s=>s.preview_url&&s.validation.valid));h.rows[0].revision++;await assert.rejects(h.call('export_marketing_campaign',{campaign_id:'campaign',expected_revision:2,review_token:review.review_token,confirmed:true}),/Reviewed slides changed/);assert.equal(h.uploads,0);assert.equal(h.approved,0);});
test('batch export checks all stored bytes, returns five numbered files and reuses the ZIP on retry',async()=>{const h=campaignFixture(),review=await h.call('get_marketing_campaign',{campaign_id:'campaign'}),args={campaign_id:'campaign',expected_revision:2,review_token:review.review_token,confirmed:true};const r=await h.call('export_marketing_campaign',args);assert.equal(r.slides.length,5);assert.match(r.zip.filename,/slides_01-05.zip$/);assert.equal(Object.keys(unzipSync(h.objects.get(h.camp.export_bundle.path))).length,5);await h.call('export_marketing_campaign',args);assert.equal(h.uploads,1);assert.equal(r.published,false);assert.equal(r.scheduled,false);});
test('corrupt stored PNG stops the complete export before upload or approval',async()=>{const h=campaignFixture(),r=await h.call('get_marketing_campaign',{campaign_id:'campaign'});h.objects.set('slide-4.png',Buffer.from('broken'));await assert.rejects(h.call('export_marketing_campaign',{campaign_id:'campaign',expected_revision:2,review_token:r.review_token,confirmed:true}),/checksum mismatch/);assert.equal(h.uploads,0);assert.equal(h.approved,0);});
test('successful update retry is recognised before the old expected revision is rejected',async()=>{const h=campaignFixture(),args={campaign_id:'campaign',expected_revision:1,idempotency_key:'same-request-key',planner_id:bg.planner_id,title:'Private campaign',slides:[]};h.db.composer_campaign_requests.push({user_id:'owner',request_key:args.idempotency_key,request_hash:await hash(canonical(args)),campaign_id:'campaign'});const r=await h.call('submit_marketing_campaign',args);assert.equal(r.revision,2);assert.equal(r.submission.replayed,true);assert.equal(h.woken,1);await assert.rejects(h.call('submit_marketing_campaign',{...args,title:'Different'}),/Idempotency key/);});

test('portrait campaign export validates 1000 by 1500 files and rejects square bytes',async()=>{const h=campaignFixture(),portrait=await sharp({create:{width:1000,height:1500,channels:3,background:'#142C35'}}).png().toBuffer();for(const r of h.rows){r.spec={...spec,output_type:'pinterest'};r.result.checksum=sha(portrait);h.objects.set(r.result.path,portrait);}const review=await h.call('get_marketing_campaign',{campaign_id:'campaign'});await h.call('export_marketing_campaign',{campaign_id:'campaign',expected_revision:2,review_token:review.review_token,confirmed:true});assert.equal(h.uploads,1);const broken=campaignFixture();for(const r of broken.rows)r.spec={...spec,output_type:'pinterest'};const wrong=await broken.call('get_marketing_campaign',{campaign_id:'campaign'});await assert.rejects(broken.call('export_marketing_campaign',{campaign_id:'campaign',expected_revision:2,review_token:wrong.review_token,confirmed:true}),/Invalid saved PNG dimensions/);assert.equal(broken.uploads,0);});
